In [1]:
import pandas as pd
import numpy as np

# 1. **데이터 설명**
1. pathway_train, pathway_test, pathway_valid : CCLE에서 pathway score 계산 한 데이터
2. ic_train, ic_test, ic_val : 민감군, 저항군 라벨
3. ccle : 유전자 raw data -> 민감군, 저항군 간 유전자 발현량이 가장 큰 유전자 3개를 genes에 저장
4. tcga: 환자 데이터로 약물 민간/저항 라벨 부착 예정

In [3]:
pathway_train = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/IRINOTECAN/train_pathway_score_IRINOTECAN.csv")
pathway_test = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/IRINOTECAN/test_pathway_score_IRINOTECAN.csv")
pathway_valid = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/IRINOTECAN/val_pathway_score_IRINOTECAN.csv")

ic_train = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/IRINOTECAN/ic_train_IRINOTECAN.csv")
ic_test = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/IRINOTECAN/ic_test_IRINOTECAN.csv")
ic_val = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/IRINOTECAN/ic_val_IRINOTECAN.csv")

ccle = pd.read_csv("C:/Users/User/비어플 의료/#_filtered_CCLE_gene_expression.csv")
ccle.index = ccle["Unnamed: 0"]




In [4]:
pathway_train.set_index("SampleID", inplace= True)
pathway_test.set_index("SampleID", inplace= True)
pathway_valid.set_index("SampleID", inplace= True)

ic_train.set_index("Unnamed: 0", inplace=True)
ic_test.set_index("Unnamed: 0", inplace=True)
ic_val.set_index("Unnamed: 0", inplace=True)


In [5]:
genes = ["MAP4K1", "WAS", "IL16"  ]

# 2. **전처리**
1. pathway score scale
2. pathway score에 대해 PCA 진행 후 90% 설명력까지 사용
3. train 기준으로 fjt하고 trest, valid, TCGA에는 transform만 해주기
4. ccle, tcga 유전자들도 sacle해주기
5. ic라벨 인코딩`

In [7]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

# 스케일링 (z-score 정규화가 되어있더라도 PCA 전에 한 번 더 정규화)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(pathway_train)
X_test_scaled = scaler.transform(pathway_test)
X_val_scaled = scaler.transform(pathway_valid)
# PCA 수행 (주성분 2개로 축소)
pca = PCA(n_components=0.90)
pathway_pca_train = pca.fit_transform(X_scaled)
pathway_pca_test  = pca.transform(X_test_scaled)
pathway_pca_valid = pca.transform(X_val_scaled)

In [8]:
pca_columns = [f"PC{i+1}" for i in range(pathway_pca_train.shape[1])]
pca_train_df_all = pd.DataFrame(pathway_pca_train, columns=pca_columns, index=pathway_train.index)
pca_train_df_all

pca_valid_df_all = pd.DataFrame(pathway_pca_valid, columns=pca_columns, index=pathway_valid.index)
pca_valid_df_all

pca_test_df_all = pd.DataFrame(pathway_pca_test, columns=pca_columns, index=pathway_test.index)
pca_test_df_all

PC1       PC2       PC3       PC4       PC5       PC6  \
SampleID                                                                  
ACH-000678  -6.273242  0.140385 -3.042808 -0.913590 -2.087817 -2.987381   
ACH-000917 -13.270443 -3.460291 -2.621795 -1.857545 -2.073129 -3.313823   
ACH-000856  -1.231217 -3.572928  1.546575  2.581406 -0.946056  2.196249   
ACH-000376   7.389518  4.650354  2.968333  1.851595  0.523655  1.137729   
ACH-000222  -7.934624 -2.103973 -6.250297  2.611709 -0.078040 -0.950124   
ACH-000805   3.937611 -0.081252  9.639593 -3.926861  2.390973  1.370180   
ACH-000847   1.002788 -6.868649  6.179821 -1.163502 -1.622648  4.607000   
ACH-000832 -12.372387  1.003224 -7.044150 -1.613194 -0.605128 -2.252476   
ACH-000749   1.089267 -3.375322  9.222696 -0.195441 -1.243255  2.503964   
ACH-000991 -18.952292 -4.907142 -2.212949 -1.198894 -2.919217 -2.499371   
ACH-000484 -18.733580 -1.691379 -0.466907 -0.115770 -0.921617 -1.445378   
ACH-000571   1.577195  2.117029  1.005065  3.227433  2.581337 -0.320722   
ACH-000391   5.486421 -3.549917  2.118608  2.995770 -1.885037  2.877375   
ACH-000561  -6.136780 -6.398515 -4.629673 -0.339756  0.020957 -2.456990   
ACH-000040  19.141879  6.419452  3.550231  3.987347  1.774107  3.096773   
ACH-000893  -3.717689  0.057255 -0.619808  1.059171  0.197849 -0.415527   
ACH-000599   1.218950  0.547336 -2.983636 -3.380504 -4.226026  1.666130   
ACH-000396   4.358851  3.477197  1.546498  1.272005 -0.044253 -1.950505   
ACH-000855  -1.413139 -0.776401 -5.082757 -0.528232 -1.317008  0.723618   
ACH-000609   5.414916  5.094909  2.658138  4.063373  0.188004 -0.836984   
ACH-000504   9.837732  4.872003  2.790337  5.673224  4.420097 -1.025310   
ACH-000956   3.228360 -6.206395  4.455300 -2.540801 -1.599006  3.067173   
ACH-000605  -8.293742 -4.290964 -2.643028 -0.943535  0.688312 -0.993463   
ACH-000018   6.022062  5.062730  1.798073  1.610994 -2.198740 -0.304598   
ACH-000649   2.563957  5.331153  0.947213  1.034548 -0.659877  1.666375   
ACH-000822   5.819237  6.408835  4.139332  0.359088  3.850953 -2.767082   
ACH-000417  -8.351452  0.773531 -5.075046 -2.398366 -3.784384 -1.709630   
ACH-000305  -3.159789  2.026785 -7.150996 -1.005190  1.238016 -1.767562   
ACH-000804   6.230944 -3.637703  9.944881  1.782938 -1.199052  0.498161   
ACH-000733  10.263324  1.549047 -2.021812  0.407407  1.061729  1.368093   
ACH-000082   8.882854  3.800150  5.366249  5.202003 -0.923658 -0.439604   
ACH-000201  -5.132138 -2.106385  3.723247  0.994990  0.794410  0.720238   
ACH-000463   7.605881 -3.937194  2.160022 -2.282644  2.034447  3.086072   
ACH-000881   0.740418  1.660231  8.098596 -4.561754  0.450058 -1.335583   
ACH-000107   2.959841  0.032096 -4.536459  0.404051 -0.298091 -0.162143   
ACH-000962   1.087121 -4.362886  2.348899  1.098777 -0.008147  1.789067   
ACH-000601  -0.424250 -3.676703  2.520699 -3.252004 -2.025297  2.596721   
ACH-000966  -6.277032 -1.477361  0.423845 -0.460535 -1.561461  1.644087   
ACH-000892  14.739606  2.206094 -0.694313  2.789756  6.711450 -0.035402   
ACH-000042  -0.739245  0.217799 -4.047772  0.911025 -0.699855 -0.388952   
ACH-000335  -4.236898  7.342677  2.083177 -4.160535 -2.695782  1.139324   
ACH-000846  -5.914390 -1.844498 -3.456292 -4.034136 -1.646106 -1.355217   
ACH-000311  -6.030641 -4.424846 -5.211754 -4.364436  2.934962  0.017267   
ACH-000062   1.015878 -1.123511 -1.079529  3.423192  4.062361  0.074491   
ACH-000778  -2.274824  8.200882 -4.608721 -4.040788 -2.840260  0.400964   
ACH-000228   4.515814  1.814431 -6.667445  2.503529  1.601225 -2.412756   
ACH-000281  -4.974522 -1.722493 -2.383391 -0.516796 -1.547635 -2.657196   
ACH-000408  -5.176832 -3.054730 -4.439102  0.334429 -1.289541 -2.615538   
ACH-000788   8.535051  2.349525  6.228100 -2.477331  1.440219  1.208090   
ACH-001075   1.923837  2.544001 -5.429679 -0.720832  0.640551 -2.073440   
ACH-000781   4.431834 -1.047674 -3.063407  0.813210  5.340451  2.017615   

                 PC7       PC8       PC9  

In [9]:
ccle = ccle[genes]
ccle_expr_train = ccle.loc[pathway_train.index]
ccle_log_train = np.log2(ccle_expr_train+1)

scaler = StandardScaler()
ccle_scaled_train = pd.DataFrame(scaler.fit_transform(ccle_log_train),
                          columns = ccle_expr_train.columns,
                          index = ccle_expr_train.index)

ccle_expr_valid = ccle.loc[pathway_valid.index]
ccle_log_valid = np.log2(ccle_expr_valid+1)

ccle_scaled_valid = pd.DataFrame(scaler.transform(ccle_log_valid),
                          columns = ccle_expr_valid.columns,
                          index = ccle_expr_valid.index)

ccle_expr_test = ccle.loc[pathway_test.index]
ccle_log_test = np.log2(ccle_expr_test+1)
ccle_scaled_test = pd.DataFrame(scaler.transform(ccle_log_test),
                          columns = ccle_expr_test.columns,
                          index = ccle_expr_test.index)

In [10]:
X_train = pd.concat([pca_train_df_all, ccle_scaled_train], axis = 1)
X_valid = pd.concat([pca_valid_df_all, ccle_scaled_valid], axis = 1)
X_test = pd.concat([pca_test_df_all, ccle_scaled_test], axis = 1)

final_scaler = StandardScaler()
X_train_final = final_scaler.fit_transform(X_train)
X_valid_final = final_scaler.transform(X_valid)
X_test_final = final_scaler.transform(X_test)


In [11]:
# 숫자 라벨로 변환 (sensitive = 1, resistant = 0)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(ic_train.iloc[:,0])
y_valid = le.fit_transform(ic_val.iloc[:,0])
y_test = le.fit_transform(ic_test.iloc[:,0])

# **3. 모델링**
1. 로지스틱, 랜덤포레스트, SVM, KNN으로 진행
2. 전처리를 R로 해야했기에 pipeline으로 묶을 수 없어 cross validation이 힘듬
3. 평가지표는 AUC, F1 score 중점으로 사용
4. 수동으로 튜닝 후 성능이 제일 좋은 모델 선택 후 TCGA 라벨 예측

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

In [32]:
## Logistic Regression
lr = LogisticRegression(C=0.001, max_iter=10000,class_weight="balanced")
lr.fit(X_train_final, y_train)
y_pred_lr = lr.predict(X_test_final)
y_proba_lr = lr.predict_proba(X_test_final)[:, 1]

## Random Forest
rf = RandomForestClassifier(n_estimators=200, max_depth=5, random_state=42,class_weight="balanced")
rf.fit(X_train_final, y_train)
y_pred_rf = rf.predict(X_test_final)
y_proba_rf = rf.predict_proba(X_test_final)[:, 1]

## Support Vector Machine (SVM)
svm = SVC(probability=True, random_state=42,class_weight="balanced")
svm.fit(X_train_final, y_train)
y_pred_svm = svm.predict(X_test_final)
y_proba_svm = svm.predict_proba(X_test_final)[:, 1]

## K-Nearest Neighbors (KNN)
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train_final, y_train)
y_pred_knn = knn.predict(X_test_final)
y_proba_knn = knn.predict_proba(X_test_final)[:, 1]

# ── AdaBoost 추가 ──
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier(
    n_estimators=50,
    random_state=42
)
ada.fit(X_train_final, y_train)

y_pred_ada   = ada.predict(X_test_final)
y_proba_ada  = ada.predict_proba(X_test_final)[:, 1]

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


In [33]:
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

print("===== Validation Set Evaluation =====")

# Logistic Regression - Validation
y_pred_lr_valid = lr.predict(X_valid_final)
y_proba_lr_valid = lr.predict_proba(X_valid_final)[:, 1]
print("\n--- Logistic Regression ---")
print(classification_report(y_valid, y_pred_lr_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_lr_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_lr_valid))

# Random Forest - Validation
y_pred_rf_valid = rf.predict(X_valid_final)
y_proba_rf_valid = rf.predict_proba(X_valid_final)[:, 1]
print("\n--- Random Forest ---")
print(classification_report(y_valid, y_pred_rf_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_rf_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_rf_valid))

# Support Vector Machine - Validation
y_pred_svm_valid = svm.predict(X_valid_final)
y_proba_svm_valid = svm.predict_proba(X_valid_final)[:, 1]
print("\n--- Support Vector Machine ---")
print(classification_report(y_valid, y_pred_svm_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_svm_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_svm_valid))

# K-Nearest Neighbors - Validation
y_pred_knn_valid = knn.predict(X_valid_final)
y_proba_knn_valid = knn.predict_proba(X_valid_final)[:, 1]
print("\n--- K-Nearest Neighbors ---")
print(classification_report(y_valid, y_pred_knn_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_knn_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_knn_valid))

# AdaBoost - Validation
y_pred_ada_valid   = ada.predict(X_valid_final)
y_proba_ada_valid  = ada.predict_proba(X_valid_final)[:, 1]
print("\n--- AdaBoost ---")
print(classification_report(y_valid, y_pred_ada_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_ada_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_ada_valid))


===== Validation Set Evaluation =====

--- Logistic Regression ---
              precision    recall  f1-score   support

   resistant       0.54      0.54      0.54        24
   sensitive       0.59      0.59      0.59        27

    accuracy                           0.57        51
   macro avg       0.57      0.57      0.57        51
weighted avg       0.57      0.57      0.57        51

ROC-AUC: 0.5524691358024691
Confusion matrix:
 [[13 11]
 [11 16]]

--- Random Forest ---
              precision    recall  f1-score   support

   resistant       0.57      0.50      0.53        24
   sensitive       0.60      0.67      0.63        27

    accuracy                           0.59        51
   macro avg       0.59      0.58      0.58        51
weighted avg       0.59      0.59      0.59        51

ROC-AUC: 0.5632716049382716
Confusion matrix:
 [[12 12]
 [ 9 18]]

--- Support Vector Machine ---
              precision    recall  f1-score   support

   resistant       0.57      0.54    

In [36]:
from sklearn.ensemble import VotingClassifier
# ── Soft Voting Ensemble ──
voting_clf = VotingClassifier(
    estimators=[
        ('lr', lr),
        ('rf', rf),
        ('svm', svm),
        ('knn', knn),
        ('ada', ada)
    ],
    voting='soft'
)
voting_clf.fit(X_train_final, y_train)

y_pred_voting  = voting_clf.predict(X_test_final)
y_proba_voting = voting_clf.predict_proba(X_test_final)[:, 1]

print("\n===== Soft Voting Ensemble =====")
print(classification_report(y_test, y_pred_voting, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_voting))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred_voting))





===== Soft Voting Ensemble =====
              precision    recall  f1-score   support

   resistant       0.55      0.46      0.50        24
   sensitive       0.58      0.67      0.62        27

    accuracy                           0.57        51
   macro avg       0.57      0.56      0.56        51
weighted avg       0.57      0.57      0.56        51

ROC-AUC: 0.5817901234567902
Confusion matrix:
 [[11 13]
 [ 9 18]]


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
