In [1]:
import pandas as pd
import numpy as np

# 1. **데이터 설명**
1. pathway_train, pathway_test, pathway_valid : CCLE에서 pathway score 계산 한 데이터
2. ic_train, ic_test, ic_val : 민감군, 저항군 라벨
3. ccle : 유전자 raw data -> 민감군, 저항군 간 유전자 발현량이 가장 큰 유전자 3개를 genes에 저장
4. tcga: 환자 데이터로 약물 민간/저항 라벨 부착 예정

In [3]:
pathway_train = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/CEDIRANIB/train_pathway_score_CEDIRANIB.csv")
pathway_test = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/CEDIRANIB/test_pathway_score_CEDIRANIB.csv")
pathway_valid = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/CEDIRANIB/val_pathway_score_CEDIRANIB.csv")

ic_train = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/CEDIRANIB/ic_train_CEDIRANIB.csv")
ic_test = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/CEDIRANIB/ic_test_CEDIRANIB.csv")
ic_val = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/CEDIRANIB/ic_val_CEDIRANIB.csv")

ccle = pd.read_csv("C:/Users/User/비어플 의료/#_filtered_CCLE_gene_expression.csv")
ccle.index = ccle["Unnamed: 0"]




In [4]:
pathway_train.set_index("SampleID", inplace= True)
pathway_test.set_index("SampleID", inplace= True)
pathway_valid.set_index("SampleID", inplace= True)

ic_train.set_index("Unnamed: 0", inplace=True)
ic_test.set_index("Unnamed: 0", inplace=True)
ic_val.set_index("Unnamed: 0", inplace=True)


In [5]:
genes = ["MAP4K1", "WAS", "SELPLG"  ]

# 2. **전처리**
1. pathway score scale
2. pathway score에 대해 PCA 진행 후 90% 설명력까지 사용
3. train 기준으로 fjt하고 trest, valid, TCGA에는 transform만 해주기
4. ccle, tcga 유전자들도 sacle해주기
5. ic라벨 인코딩`

In [7]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

# 스케일링 (z-score 정규화가 되어있더라도 PCA 전에 한 번 더 정규화)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(pathway_train)
X_test_scaled = scaler.transform(pathway_test)
X_val_scaled = scaler.transform(pathway_valid)
# PCA 수행 (주성분 2개로 축소)
pca = PCA(n_components=0.90)
pathway_pca_train = pca.fit_transform(X_scaled)
pathway_pca_test  = pca.transform(X_test_scaled)
pathway_pca_valid = pca.transform(X_val_scaled)

In [8]:
pca_columns = [f"PC{i+1}" for i in range(pathway_pca_train.shape[1])]
pca_train_df_all = pd.DataFrame(pathway_pca_train, columns=pca_columns, index=pathway_train.index)
pca_train_df_all

pca_valid_df_all = pd.DataFrame(pathway_pca_valid, columns=pca_columns, index=pathway_valid.index)
pca_valid_df_all

pca_test_df_all = pd.DataFrame(pathway_pca_test, columns=pca_columns, index=pathway_test.index)
pca_test_df_all

PC1        PC2       PC3       PC4       PC5       PC6  \
SampleID                                                                   
ACH-000823  -8.857699  -2.215490 -1.120246 -0.823611 -2.373167  3.274626   
ACH-000678  -4.497151   0.492021  3.379773 -1.874305 -2.465482  2.585348   
ACH-000138  -4.417090   2.944893  5.817551 -1.096988 -1.538579 -0.870846   
ACH-000704   9.330632  -5.256672  0.135887  0.666500  1.387105 -1.339309   
ACH-000276   6.133993  -5.420277 -1.862820 -2.748638 -0.719810  0.642280   
ACH-000035   9.294253  -1.839145  0.850174 -3.068360  1.075761  0.446220   
ACH-000223   7.136013  -3.612972  4.283164 -1.643811 -0.267390  1.908344   
ACH-000971   2.304680  -4.765937 -2.286625  4.479442 -3.679099  0.214857   
ACH-000858 -20.969666   0.239734  0.705437  0.643144 -1.972278  0.738154   
ACH-000991 -19.712625  -4.696318  0.336735  0.401932 -2.452300  0.371185   
ACH-000186   8.457109   5.985153  4.771176 -0.537970 -0.200711  0.700083   
ACH-000711  -0.195745  -1.480010  2.629314 -1.795350 -1.918751  1.923211   
ACH-000662  -0.209841   1.586428  3.715051  4.540423 -2.183117  1.547669   
ACH-000484 -21.637669  -0.987882 -0.134071 -0.763432 -1.026278 -1.218353   
ACH-000819  -0.048183   0.050119 -3.476201 -0.155982 -0.177185 -1.323569   
ACH-000437 -19.038189   1.915035 -4.313743 -1.943213 -1.806382  0.581691   
ACH-000893  -4.626892  -0.917424 -0.480154 -0.548818 -0.553072 -0.400725   
ACH-000273   9.731304   1.821805 -2.296373 -5.318334  2.878788 -0.939385   
ACH-000947  13.725553  -8.511089 -3.918214  1.564913  1.281961 -0.753529   
ACH-000396   5.854223   3.399618 -3.212547 -1.186678 -2.197584  2.474785   
ACH-000414   5.422639  -3.762652  4.042664  3.960234  2.691162 -3.923331   
ACH-000572   3.374869  -2.516644 -8.226772  2.782582  4.354046  0.424976   
ACH-000090  -8.747685  -0.512520 -1.734503  0.111196 -1.747189  1.194710   
ACH-000092   7.830606   6.910711  0.078088 -1.512208  1.160961 -2.105025   
ACH-000264   9.173632  -1.903832 -0.895980 -1.021808  0.236852 -1.354574   
ACH-000974  -6.653275  -1.296921  2.572150 -1.066933 -1.021854 -1.230449   
ACH-000243   7.726916   1.310354  3.499525  0.864927 -2.284702  2.523272   
ACH-000822   5.477443   4.771070 -5.610539 -0.647449  6.981785  1.851258   
ACH-000812   2.214269  -0.609583 -7.362048  1.153809  5.684784 -0.461518   
ACH-000730  -2.515698  -2.195092 -7.331992  2.407424  5.086573 -0.258335   
ACH-000305  -4.072455   3.047864  6.176765 -2.001583  0.321855  0.898292   
ACH-000171  -9.669649   0.893851  0.715522  0.207426  2.328010 -3.380723   
ACH-000835   4.162683  11.378551 -1.681536  1.836237 -1.078923  2.578396   
ACH-000189   7.319484   6.500862  4.745379 -4.085657  2.156943 -1.987018   
ACH-000395   2.909284  -8.037514 -3.497119  1.122589 -0.304135 -1.341202   
ACH-000107   6.594468  -0.505828  6.882206 -0.385683 -0.483525 -0.139854   
ACH-000563   8.324772   1.864722  2.386551  0.652524 -2.134967  2.396115   
ACH-000244 -13.128309   2.278247 -6.541077 -4.102776  1.001339 -0.522565   
ACH-000841   8.289158  -3.184585  4.826363  3.022948  0.787148 -2.518510   
ACH-000452 -12.415499  -1.035958 -3.300629 -5.407481 -1.908456  3.421666   
ACH-000860   6.468157  -4.065428  0.762011  2.401685 -1.147191  0.048175   
ACH-000558   2.180499   2.711608 -5.367744 -3.297784 -0.519286 -0.257010   
ACH-000207  -0.853854   3.789307  3.329372  1.619999 -3.144233  2.999646   
ACH-000311  -7.521610  -4.709669  4.702959  3.214523  2.979140 -3.035245   
ACH-000496   0.378352  -0.096918 -0.981724  1.711948  2.880281 -3.383292   
ACH-000911  -4.362209   4.938861  3.434311  3.401155 -3.679388  1.470312   
ACH-000869   2.380587  -3.057138  2.597653 -3.431224  0.245181  1.494131   
ACH-000023   7.845919   0.476720 -2.040387  2.684464 -1.285869 -0.358657   
ACH-000663  -1.118977  -0.387902  0.882557  1.132483 -1.689411 -2.371947   
ACH-000781   3.684799  -2.131912  1.564759  0.619627  3.047324 -3.585723   
ACH-000750   1.543674  10.405781 -2.150057  3.261941 -0.606685  0.

In [9]:
ccle = ccle[genes]
ccle_expr_train = ccle.loc[pathway_train.index]
ccle_log_train = np.log2(ccle_expr_train+1)

scaler = StandardScaler()
ccle_scaled_train = pd.DataFrame(scaler.fit_transform(ccle_log_train),
                          columns = ccle_expr_train.columns,
                          index = ccle_expr_train.index)

ccle_expr_valid = ccle.loc[pathway_valid.index]
ccle_log_valid = np.log2(ccle_expr_valid+1)

ccle_scaled_valid = pd.DataFrame(scaler.transform(ccle_log_valid),
                          columns = ccle_expr_valid.columns,
                          index = ccle_expr_valid.index)

ccle_expr_test = ccle.loc[pathway_test.index]
ccle_log_test = np.log2(ccle_expr_test+1)
ccle_scaled_test = pd.DataFrame(scaler.transform(ccle_log_test),
                          columns = ccle_expr_test.columns,
                          index = ccle_expr_test.index)

In [10]:
X_train = pd.concat([pca_train_df_all, ccle_scaled_train], axis = 1)
X_valid = pd.concat([pca_valid_df_all, ccle_scaled_valid], axis = 1)
X_test = pd.concat([pca_test_df_all, ccle_scaled_test], axis = 1)

final_scaler = StandardScaler()
X_train_final = final_scaler.fit_transform(X_train)
X_valid_final = final_scaler.transform(X_valid)
X_test_final = final_scaler.transform(X_test)


In [11]:
# 숫자 라벨로 변환 (sensitive = 1, resistant = 0)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(ic_train.iloc[:,0])
y_valid = le.fit_transform(ic_val.iloc[:,0])
y_test = le.fit_transform(ic_test.iloc[:,0])

# **3. 모델링**
1. 로지스틱, 랜덤포레스트, SVM, KNN으로 진행
2. 전처리를 R로 해야했기에 pipeline으로 묶을 수 없어 cross validation이 힘듬
3. 평가지표는 AUC, F1 score 중점으로 사용
4. 수동으로 튜닝 후 성능이 제일 좋은 모델 선택 후 TCGA 라벨 예측

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

In [14]:
## Logistic Regression
lr = LogisticRegression(C=0.01, max_iter=10000)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
y_proba_lr = lr.predict_proba(X_test)[:, 1]

## Random Forest
rf = RandomForestClassifier(n_estimators=250, max_depth=5, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
y_proba_rf = rf.predict_proba(X_test)[:, 1]

## Support Vector Machine (SVM)
svm = SVC(probability=True, random_state=42)
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)
y_proba_svm = svm.predict_proba(X_test)[:, 1]

## K-Nearest Neighbors (KNN)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)
y_proba_knn = knn.predict_proba(X_test)[:, 1]

# ── AdaBoost 추가 ──
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier(
    n_estimators=50,
    random_state=42
)
ada.fit(X_train_final, y_train)

y_pred_ada   = ada.predict(X_test_final)
y_proba_ada  = ada.predict_proba(X_test_final)[:, 1]

C:\Users\USER\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


In [15]:
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

print("===== Validation Set Evaluation =====")

# Logistic Regression - Validation
y_pred_lr_valid = lr.predict(X_valid)
y_proba_lr_valid = lr.predict_proba(X_valid)[:, 1]
print("\n--- Logistic Regression ---")
print(classification_report(y_valid, y_pred_lr_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_lr_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_lr_valid))

# Random Forest - Validation
y_pred_rf_valid = rf.predict(X_valid)
y_proba_rf_valid = rf.predict_proba(X_valid)[:, 1]
print("\n--- Random Forest ---")
print(classification_report(y_valid, y_pred_rf_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_rf_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_rf_valid))

# Support Vector Machine - Validation
y_pred_svm_valid = svm.predict(X_valid)
y_proba_svm_valid = svm.predict_proba(X_valid)[:, 1]
print("\n--- Support Vector Machine ---")
print(classification_report(y_valid, y_pred_svm_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_svm_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_svm_valid))

# K-Nearest Neighbors - Validation
y_pred_knn_valid = knn.predict(X_valid)
y_proba_knn_valid = knn.predict_proba(X_valid)[:, 1]
print("\n--- K-Nearest Neighbors ---")
print(classification_report(y_valid, y_pred_knn_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_knn_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_knn_valid))

# AdaBoost - Validation
y_pred_ada_valid   = ada.predict(X_valid_final)
y_proba_ada_valid  = ada.predict_proba(X_valid_final)[:, 1]
print("\n--- AdaBoost ---")
print(classification_report(y_valid, y_pred_ada_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_ada_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_ada_valid))


===== Validation Set Evaluation =====

--- Logistic Regression ---
              precision    recall  f1-score   support

   resistant       0.53      0.62      0.57        26
   sensitive       0.52      0.44      0.48        25

    accuracy                           0.53        51
   macro avg       0.53      0.53      0.52        51
weighted avg       0.53      0.53      0.53        51

ROC-AUC: 0.5446153846153846
Confusion matrix:
 [[16 10]
 [14 11]]

--- Random Forest ---
              precision    recall  f1-score   support

   resistant       0.53      0.62      0.57        26
   sensitive       0.52      0.44      0.48        25

    accuracy                           0.53        51
   macro avg       0.53      0.53      0.52        51
weighted avg       0.53      0.53      0.53        51

ROC-AUC: 0.48307692307692307
Confusion matrix:
 [[16 10]
 [14 11]]

--- Support Vector Machine ---
              precision    recall  f1-score   support

   resistant       0.48      0.50   

In [16]:
from sklearn.ensemble import VotingClassifier
# ── Soft Voting Ensemble ──
voting_clf = VotingClassifier(
    estimators=[
        ('lr', lr),
        ('rf', rf),
        ('svm', svm),
        ('knn', knn),
        ('ada', ada)
    ],
    voting='soft'
)
voting_clf.fit(X_train_final, y_train)

y_pred_voting  = voting_clf.predict(X_test_final)
y_proba_voting = voting_clf.predict_proba(X_test_final)[:, 1]

print("\n===== Soft Voting Ensemble =====")
print(classification_report(y_test, y_pred_voting, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_voting))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred_voting))





===== Soft Voting Ensemble =====
              precision    recall  f1-score   support

   resistant       0.53      0.62      0.57        26
   sensitive       0.52      0.44      0.48        25

    accuracy                           0.53        51
   macro avg       0.53      0.53      0.52        51
weighted avg       0.53      0.53      0.53        51

ROC-AUC: 0.6
Confusion matrix:
 [[16 10]
 [14 11]]


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
