In [1]:
import pandas as pd
import numpy as np

# 1. **데이터 설명**
1. pathway_train, pathway_test, pathway_valid : CCLE에서 pathway score 계산 한 데이터
2. ic_train, ic_test, ic_val : 민감군, 저항군 라벨
3. ccle : 유전자 raw data -> 민감군, 저항군 간 유전자 발현량이 가장 큰 유전자 3개를 genes에 저장
4. tcga: 환자 데이터로 약물 민간/저항 라벨 부착 예정

In [3]:
pathway_train = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/MK_1775/train_pathway_score_MK.1775.csv")
pathway_test = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/MK_1775/test_pathway_score_MK.1775.csv")
pathway_valid = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/MK_1775/val_pathway_score_MK.1775.csv")

ic_train = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/MK_1775/ic_train_MK.1775.csv")
ic_test = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/MK_1775/ic_test_MK.1775.csv")
ic_val = pd.read_csv("C:/Users/USER/비어플 의료/0415_final/pathway scores/MK_1775/ic_val_MK.1775.csv")

ccle = pd.read_csv("C:/Users/User/비어플 의료/#_filtered_CCLE_gene_expression.csv")
ccle.index = ccle["Unnamed: 0"]




In [4]:
pathway_train.set_index("SampleID", inplace= True)
pathway_test.set_index("SampleID", inplace= True)
pathway_valid.set_index("SampleID", inplace= True)

ic_train.set_index("Unnamed: 0", inplace=True)
ic_test.set_index("Unnamed: 0", inplace=True)
ic_val.set_index("Unnamed: 0", inplace=True)


In [5]:
genes = ["MAP4K1", "WAS", "CCND2"  ]

# 2. **전처리**
1. pathway score scale
2. pathway score에 대해 PCA 진행 후 90% 설명력까지 사용
3. train 기준으로 fjt하고 trest, valid, TCGA에는 transform만 해주기
4. ccle, tcga 유전자들도 sacle해주기
5. ic라벨 인코딩`

In [7]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

# 스케일링 (z-score 정규화가 되어있더라도 PCA 전에 한 번 더 정규화 추천)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(pathway_train)
X_test_scaled = scaler.transform(pathway_test)
X_val_scaled = scaler.transform(pathway_valid)
# PCA 수행 (주성분 2개로 축소)
pca = PCA(n_components=0.90)
pathway_pca_train = pca.fit_transform(X_scaled)
pathway_pca_test  = pca.transform(X_test_scaled)
pathway_pca_valid = pca.transform(X_val_scaled)

In [8]:
pca_columns = [f"PC{i+1}" for i in range(pathway_pca_train.shape[1])]
pca_train_df_all = pd.DataFrame(pathway_pca_train, columns=pca_columns, index=pathway_train.index)
pca_train_df_all

pca_valid_df_all = pd.DataFrame(pathway_pca_valid, columns=pca_columns, index=pathway_valid.index)
pca_valid_df_all

pca_test_df_all = pd.DataFrame(pathway_pca_test, columns=pca_columns, index=pathway_test.index)
pca_test_df_all

PC1       PC2       PC3       PC4       PC5       PC6  \
SampleID                                                                  
ACH-000625  -0.961157 -2.729453 -2.194106 -1.251971  0.161081 -1.769774   
ACH-000035  10.202321  5.344649  1.044295  0.608017  1.239826 -1.679748   
ACH-000223   5.716065  2.527377  2.409965  1.033711 -0.022761 -2.092238   
ACH-000978   2.203899 -5.945385 -6.112346  0.359050 -0.664158 -0.322713   
ACH-000848  -1.911603 -7.792956 -2.816152 -0.911132  0.388582  0.198316   
ACH-000481  -4.868218 -8.355199  3.299067 -2.232769 -1.324490  0.004547   
ACH-000858 -20.669690 -1.222050  2.068138 -1.972509 -1.366380 -1.348433   
ACH-000684  -1.343843  8.673382  1.754426  1.810389  1.865864  4.338824   
ACH-000943 -14.975195 -5.380253 -3.898431 -2.768222 -1.296940  2.420226   
ACH-000329   4.291714  7.580563 -2.725927  1.572583  1.298477 -0.962217   
ACH-000561  -6.673643 -3.834006  2.681626  0.377853 -1.510225 -0.947426   
ACH-000562   1.754760  2.160704  2.962783 -1.330898  0.124684  1.125277   
ACH-000437 -17.973509  2.807381 -1.595704 -2.599707  1.032401 -1.352558   
ACH-000924  11.376475 -0.161034 -0.872610  1.039159  0.931204 -0.176789   
ACH-000674 -11.110811 -5.469798  2.837292  0.244336 -1.215289  1.383852   
ACH-000955   0.821694 -7.583514  0.910495  0.764223  0.496252  0.279115   
ACH-000188  -8.614732  7.173329  2.170466 -1.162364 -1.546671 -1.813255   
ACH-000118   2.433334  1.558993  3.149069 -1.182266 -1.027039 -0.023204   
ACH-000637  -5.606379  3.330553  2.308735 -1.088382 -0.778907 -1.156171   
ACH-000434   1.371001  0.116826 -3.776808 -1.371091 -1.486755  2.023971   
ACH-000132   3.700235  3.378782 -0.654517 -1.670346  1.454081 -0.048590   
ACH-000652 -20.649974 -3.221619 -0.327686 -3.577766  0.018235  0.824528   
ACH-000007  -3.620021 -7.590150  2.832954 -0.425246  0.007157  2.348488   
ACH-000649   5.185961  7.958743 -0.175767 -0.185663  1.709456  3.388311   
ACH-000021  -2.673089  0.332425  0.095662 -1.785321  1.106297  2.974633   
ACH-000730  -0.162484 -2.533674 -4.947657  2.246753 -1.915499 -0.792583   
ACH-000976  -4.098025  5.444012  5.215058 -3.348382 -0.144643  3.730486   
ACH-000535   3.771284  4.632170  5.908165  0.371560 -1.589843 -0.532934   
ACH-000916  -1.135518 -4.011172  4.514393  2.457901 -0.279350 -0.314764   
ACH-000137   6.930895  3.556816 -1.590225  3.800262  2.477444 -0.457524   
ACH-000147  -0.834345 -7.090639 -3.817061  1.066130  0.784718 -3.242920   
ACH-000107   7.128442  3.940632  6.087925  0.018756  0.315042 -0.008084   
ACH-000473   2.415102 -0.651323  0.433529  0.842807 -1.456279 -3.392925   
ACH-000192  -6.407647 -6.130195 -4.656524 -0.732518  1.271200 -1.632150   
ACH-000966  -5.803795 -1.938292 -1.532167 -2.046082 -0.199526  0.480958   
ACH-000892  17.375062  4.300321  0.120674  5.720449  0.499479 -0.700833   
ACH-000352  10.727162 -4.506589 -4.498534 -0.465810 -0.325090 -4.175184   
ACH-000416  10.225687  2.956336 -2.417541 -2.382763 -1.403460  1.947790   
ACH-000191   5.270937  3.957519  4.248812  3.452720  1.438055  3.632845   
ACH-000841   7.956563 -1.601681  3.436269  1.588753 -0.303880  2.497429   
ACH-000720  -1.933404  4.843999 -0.911709  0.382456  2.387963 -2.400296   
ACH-000958 -21.850147 -5.722582 -0.472920 -3.033496  0.613053 -0.895831   
ACH-000228   7.526229  5.854457  4.075964  1.061073  0.312639 -2.376698   
ACH-000521   9.044207  1.621448  0.375833  2.005668  1.139953  1.197610   
ACH-000384  13.122477  1.092378  2.500358  4.010721 -0.677725 -0.234135   
ACH-000775   8.400806 -1.832139 -1.341253  0.424018 -0.391249  0.246707   
ACH-000510   2.219790 -0.760404 -4.879508 -3.038552 -0.914106  1.508711   
ACH-000469 -21.704050  3.163223 -2.077937 -4.004310  1.084835 -1.847090   
ACH-000781   6.026637  1.063235  3.064090  2.872705  0.424386  1.649490   
ACH-000968   9.404635 -1.205035 -6.284978  3.880341 -1.823389 -2.874151   
ACH-000052   8.977905 -2.101111 -5.927976  0.555173 -0.918711  1.369103   

                 PC7       PC8       PC9  

In [9]:
ccle = ccle[genes]
ccle_expr_train = ccle.loc[pathway_train.index]
ccle_log_train = np.log2(ccle_expr_train+1)

scaler = StandardScaler()
ccle_scaled_train = pd.DataFrame(scaler.fit_transform(ccle_log_train),
                          columns = ccle_expr_train.columns,
                          index = ccle_expr_train.index)

ccle_expr_valid = ccle.loc[pathway_valid.index]
ccle_log_valid = np.log2(ccle_expr_valid+1)

ccle_scaled_valid = pd.DataFrame(scaler.transform(ccle_log_valid),
                          columns = ccle_expr_valid.columns,
                          index = ccle_expr_valid.index)

ccle_expr_test = ccle.loc[pathway_test.index]
ccle_log_test = np.log2(ccle_expr_test+1)
ccle_scaled_test = pd.DataFrame(scaler.transform(ccle_log_test),
                          columns = ccle_expr_test.columns,
                          index = ccle_expr_test.index)

In [10]:
X_train = pd.concat([pca_train_df_all, ccle_scaled_train], axis = 1)
X_valid = pd.concat([pca_valid_df_all, ccle_scaled_valid], axis = 1)
X_test = pd.concat([pca_test_df_all, ccle_scaled_test], axis = 1)

final_scaler = StandardScaler()
X_train_final = final_scaler.fit_transform(X_train)
X_valid_final = final_scaler.transform(X_valid)
X_test_final = final_scaler.transform(X_test)


In [11]:
# 숫자 라벨로 변환 (sensitive = 1, resistant = 0)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(ic_train.iloc[:,0])
y_valid = le.fit_transform(ic_val.iloc[:,0])
y_test = le.fit_transform(ic_test.iloc[:,0])

# **3. 모델링**
1. 로지스틱, 랜덤포레스트, SVM, KNN으로 진행
2. 전처리를 R로 해야했기에 pipeline으로 묶을 수 없어 cross validation이 힘듬
3. 평가지표는 AUC, F1 score 중점으로 사용
4. 수동으로 튜닝 후 성능이 제일 좋은 모델 선택 후 TCGA 라벨 예측

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

In [14]:
## Logistic Regression
lr = LogisticRegression(C=0.01, max_iter=10000)
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
y_proba_lr = lr.predict_proba(X_test)[:, 1]

## Random Forest
rf = RandomForestClassifier(n_estimators=200, max_depth=5, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
y_proba_rf = rf.predict_proba(X_test)[:, 1]

## Support Vector Machine (SVM)
svm = SVC(probability=True, random_state=42)
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)
y_proba_svm = svm.predict_proba(X_test)[:, 1]

## K-Nearest Neighbors (KNN)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)
y_proba_knn = knn.predict_proba(X_test)[:, 1]

# ── AdaBoost 추가 ──
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier(
    n_estimators=50,
    random_state=42
)
ada.fit(X_train_final, y_train)

y_pred_ada   = ada.predict(X_test_final)
y_proba_ada  = ada.predict_proba(X_test_final)[:, 1]


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


In [15]:
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

print("===== Validation Set Evaluation =====")

# Logistic Regression - Validation
y_pred_lr_valid = lr.predict(X_valid)
y_proba_lr_valid = lr.predict_proba(X_valid)[:, 1]
print("\n--- Logistic Regression ---")
print(classification_report(y_valid, y_pred_lr_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_lr_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_lr_valid))

# Random Forest - Validation
y_pred_rf_valid = rf.predict(X_valid)
y_proba_rf_valid = rf.predict_proba(X_valid)[:, 1]
print("\n--- Random Forest ---")
print(classification_report(y_valid, y_pred_rf_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_rf_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_rf_valid))

# Support Vector Machine - Validation
y_pred_svm_valid = svm.predict(X_valid)
y_proba_svm_valid = svm.predict_proba(X_valid)[:, 1]
print("\n--- Support Vector Machine ---")
print(classification_report(y_valid, y_pred_svm_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_svm_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_svm_valid))

# K-Nearest Neighbors - Validation
y_pred_knn_valid = knn.predict(X_valid)
y_proba_knn_valid = knn.predict_proba(X_valid)[:, 1]
print("\n--- K-Nearest Neighbors ---")
print(classification_report(y_valid, y_pred_knn_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_knn_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_knn_valid))
# AdaBoost - Validation
y_pred_ada_valid   = ada.predict(X_valid_final)
y_proba_ada_valid  = ada.predict_proba(X_valid_final)[:, 1]
print("\n--- AdaBoost ---")
print(classification_report(y_valid, y_pred_ada_valid, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_valid, y_proba_ada_valid))
print("Confusion matrix:\n", confusion_matrix(y_valid, y_pred_ada_valid))


===== Validation Set Evaluation =====

--- Logistic Regression ---
              precision    recall  f1-score   support

   resistant       0.44      0.35      0.39        23
   sensitive       0.55      0.64      0.59        28

    accuracy                           0.51        51
   macro avg       0.49      0.50      0.49        51
weighted avg       0.50      0.51      0.50        51

ROC-AUC: 0.4751552795031056
Confusion matrix:
 [[ 8 15]
 [10 18]]

--- Random Forest ---
              precision    recall  f1-score   support

   resistant       0.50      0.22      0.30        23
   sensitive       0.56      0.82      0.67        28

    accuracy                           0.55        51
   macro avg       0.53      0.52      0.48        51
weighted avg       0.53      0.55      0.50        51

ROC-AUC: 0.5248447204968945
Confusion matrix:
 [[ 5 18]
 [ 5 23]]

--- Support Vector Machine ---
              precision    recall  f1-score   support

   resistant       0.36      0.35    

In [16]:
from sklearn.ensemble import VotingClassifier
# ── Soft Voting Ensemble ──
voting_clf = VotingClassifier(
    estimators=[
        ('lr', lr),
        ('rf', rf),
        ('svm', svm),
        ('knn', knn),
        ('ada', ada)
    ],
    voting='soft'
)
voting_clf.fit(X_train_final, y_train)

y_pred_voting  = voting_clf.predict(X_test_final)
y_proba_voting = voting_clf.predict_proba(X_test_final)[:, 1]

print("\n===== Soft Voting Ensemble =====")
print(classification_report(y_test, y_pred_voting, target_names=le.classes_))
print("ROC-AUC:", roc_auc_score(y_test, y_proba_voting))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred_voting))





===== Soft Voting Ensemble =====
              precision    recall  f1-score   support

   resistant       0.33      0.22      0.26        23
   sensitive       0.50      0.64      0.56        28

    accuracy                           0.45        51
   macro avg       0.42      0.43      0.41        51
weighted avg       0.42      0.45      0.43        51

ROC-AUC: 0.5
Confusion matrix:
 [[ 5 18]
 [10 18]]


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
